version: "3"

services:
  web:
    build:
      context: ./bin/nginx
    container_name: "nginx"
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./config/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./config/ssl:/etc/letsencrypt"
      - "./logs/nginx:/var/log/nginx"
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - mysql
    networks:
      - app_network_nginx

  # PHP
  php:
    platform: linux/amd64
    build:
      context: ./bin/${PHPVERSION}
    container_name: "${PHPVERSION}"
    restart: unless-stopped
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
    networks:
      - app_network_nginx

  # Mysql
  mysql:
    platform: linux/amd64
    build:
      context: "./bin/${DATABASE}"
    container_name: "nginx_${DATABASE}"
    restart: unless-stopped
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app_network_nginx

  # Phpmyadmin
  # phpmyadmin:
  #   platform: linux/amd64
  #   image: phpmyadmin/phpmyadmin
  #   container_name: 'phpmyadmin'
  #   restart: unless-stopped
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_PORT: 3306
  #     PMA_USER: root
  #     PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     UPLOAD_LIMIT: 400M
  #   ports:
  #     - '${HOST_MACHINE_PMA_PORT}:80'
  #   volumes:
  #     - /sessions
  #     - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
  #   networks:
  #     - app_network_nginx

  # Portainer
  # portainer:
  #   container_name: 'portainer'
  #   image: portainer/portainer-ce:latest
  #   ports:
  #     - '${PORTAINER_PORT}:9443'
  #   volumes:
  #     - ${PORTAINER_DATA_DIR}:/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: unless-stopped

# Networks
networks:
  app_network_nginx:
    driver: bridge
